version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: ai-hotel-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ai-hotel

  # Backend API (Development mode with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-hotel-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/ai-hotel
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongodb_data:
